# Generated by Django 2.2 on 2019-04-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('time', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
