# Generated by Django 2.2 on 2019-04-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
